#!/usr/bin/env python3
"""
scripts/curriculum/banks/aptitude_bank_16_30.py
Authentic, Non-Template Aptitude MCQs for Days 16 to 30 (10 MCQs per day = 150 MCQs).
"""

BANKS_16_30 = {
    16: [  # Seating Arrangement
        ("Eight friends A, B, C, D, E, F, G, H sit around a circular table facing the center. A sits third to the right of B. C sits second to the left of A. Who sits directly between B and C if E sits opposite A?", {"A": "D or G", "B": "H", "C": "F", "D": "Cannot be determined"}, "D", "Without additional placement data for remaining positions D, F, G, H, the exact occupant between B and C cannot be uniquely determined."),
        ("Five girls P, Q, R, S, T sit in a row facing North. Q is to the immediate right of S. T is to the left of R and immediate right of P. S is to the right of R. Who sits in the middle?", {"A": "R", "B": "S", "C": "T", "D": "Q"}, "A", "Order from left to right: P, T, R, S, Q. The middle position (3rd of 5) is occupied by R."),
        ("Six persons A, B, C, D, E, F sit in two rows of three each, facing each other. E is not at the end of any row. D is second to the left of F. C, the neighbor of E, is diagonally opposite D. B is neighbor of F. Who is opposite B?", {"A": "E", "B": "C", "C": "A", "D": "F"}, "A", "Top row: D, A, C; Bottom row: F, B, E. E sits opposite B."),
        ("A, B, C, D, E are sitting in a circle facing the center. A is between E and D. B is to the right of D. Who is to the immediate left of B?", {"A": "D", "B": "C", "C": "E", "D": "A"}, "A", "In clockwise order: E, A, D, B, C. Immediate left of B (moving clockwise) is D."),
        ("In a row of 40 students facing North, Amit is 18th from the left end and Sumit is 24th from the right end. How many students sit between them?", {"A": "0 (They overlap)", "B": "2", "C": "4", "D": "6"}, "A", "Sum of positions = 18 + 24 = 42 > 40. Overlapping students = (18 + 24) - 40 - 2 = 42 - 42 = 0 students between them."),
        ("Six friends J, K, L, M, N, O sit around a hexagon table facing center. J is opposite M. K is second to left of J. O is between J and K. L is opposite O. Who is between M and L?", {"A": "N", "B": "K", "C": "O", "D": "J"}, "A", "Placements: J, O, K, M, N, L. N sits directly between M and L."),
        ("In a row of children, Ravi is 4th from left and Shyam is 7th from right. When they interchange places, Ravi becomes 15th from left. How many children are in the row?", {"A": "21", "B": "22", "C": "20", "D": "23"}, "A", "Total children = (Ravi's new left position) + (Shyam's original right position) - 1 = 15 + 7 - 1 = 21."),
        ("Seven people A, B, C, D, E, F, G sit in a line facing North. D sits in the middle. A and G are at extreme ends. B sits immediate right of D. F is between A and C. Who sits between B and G?", {"A": "E", "B": "C", "C": "F", "D": "D"}, "A", "Order: A, F, C, D, B, E, G. E sits directly between B and G."),
        ("Eight executives sit around a square conference table, two on each side facing the center. If Raj sits opposite Priya, who sits to Priya's left?", {"A": "Dependent on corner adjacency", "B": "Raj", "C": "Neither", "D": "Cannot be determined without side parity"}, "D", "Table configuration requires side and corner assignments to resolve lateral adjacency."),
        ("In a class of 45 students, a boy is ranked 20th. When two boys join, his rank drops by 1. What is his new rank from the bottom?", {"A": "27th", "B": "28th", "C": "26th", "D": "25th"}, "A", "New total students = 45 + 2 = 47. His new top rank = 20 + 1 = 21st. Rank from bottom = (47 - 21) + 1 = 27th.")
    ],

    17: [  # Coding-Decoding
        ("In a certain code language, 'COMPUTER' is written as 'RFUVQNPC'. How is 'MEDICINE' written in that code?", {"A": "EOJDEJFM", "B": "EOJDJEFM", "C": "EOJDEJGM", "D": "MFEJDJOE"}, "A", "Reverse the word and replace each letter: First and last remain reversed, intermediate letters shift +1. 'MEDICINE' becomes 'EOJDEJFM'."),
        ("If 'DELHI' is coded as 73541 and 'CALCUTTA' as 82589662, how can 'CALICUT' be coded?", {"A": "8251896", "B": "8251396", "C": "8254362", "D": "8251862"}, "A", "Direct letter-to-digit substitution: C=8, A=2, L=5, I=1, C=8, U=9, T=6 => 8251896."),
        ("If 'ROAD' is written as 'URDG', how is 'SWAN' written in that code?", {"A": "VZDQ", "B": "VXDQ", "C": "VZCQ", "D": "UXDQ"}, "A", "Each letter is shifted forward by +3 positions: S(+3)->V, W(+3)->Z, A(+3)->D, N(+3)->Q => VZDQ."),
        ("In a code language, if 'WATER' is written as 'YCVGT', how is 'HIKER' written?", {"A": "JKMGT", "B": "JKNGT", "C": "KLMGT", "D": "JJNGT"}, "A", "Each letter advances by +2 positions in the alphabet: H->J, I->K, K->M, E->G, R->T => JKMGT."),
        ("If 'FRIEND' is coded as 'HUMJTK', how is 'CANDLE' coded?", {"A": "EDRIRL", "B": "ESJFME", "C": "DEQJQM", "D": "FYOBOC"}, "A", "Shifts increase progressively: +2, +3, +4, +5, +6, +7. C(+2)->E, A(+3)->D, N(+4)->R, D(+5)->I, L(+6)->R, E(+7)->L => EDRIRL."),
        ("In a certain code, '253' means 'books are old', '546' means 'man is old', and '378' means 'buy good books'. What digit stands for 'are'?", {"A": "2", "B": "5", "C": "3", "D": "4"}, "A", "In 253 and 546, common word is 'old' and common digit is '5'. In 253 and 378, common word is 'books' and digit is '3'. Therefore in '253', remaining digit '2' represents 'are'."),
        ("If 'ZEBRA' is written as 2652181, how is 'COBRA' written?", {"A": "3152181", "B": "30152181", "C": "31521818", "D": "3152118"}, "A", "Letters are replaced by their standard 1-based alphabetical positions: C=3, O=15, B=2, R=18, A=1 => 3152181."),
        ("If 'RAIN' is coded as '8$%6' and 'MORE' is coded as '7#8@', how is 'REMAIN' written?", {"A": "8@7$6%", "B": "8@7$%6", "C": "7@8$%6", "D": "8$%@76"}, "B", "Direct character-symbol mapping: R=8, E=@, M=7, A=$, I=%, N=6 => 8@7$%6."),
        ("In a certain code, 'SYSTEM' is coded as 'SYSMET' and 'NEARER' as 'AENRER'. What is the code for 'FRACTION'?", {"A": "CARFNOIT", "B": "CARFTION", "C": "ARFCNOIT", "D": "CARFNOIT"}, "A", "Divide into two equal 4-letter halves and reverse each half independently: FRAC -> CARF; TION -> NOIT => CARFNOIT."),
        ("If 'GIVE' is coded as '5137' and 'BAT' as '924', how is 'GATE' coded?", {"A": "5247", "B": "5427", "C": "5724", "D": "2547"}, "A", "Direct substitution: G=5, A=2, T=4, E=7 => 5247.")
    ],

    18: [  # Series Completion
        ("Find the next number in the series: 3, 7, 15, 31, 63, ?", {"A": "127", "B": "126", "C": "125", "D": "128"}, "A", "Each term follows the rule: next = 2 * prev + 1. 2 * 63 + 1 = 127."),
        ("What is the next term in the sequence: 2, 5, 10, 17, 26, 37, ?", {"A": "50", "B": "48", "C": "49", "D": "52"}, "A", "Differences between consecutive terms are odd numbers: +3, +5, +7, +9, +11, +13. 37 + 13 = 50 (or n^2 + 1: 7^2 + 1 = 50)."),
        ("Find the missing number: 4, 9, 25, 49, 121, ?", {"A": "169", "B": "144", "C": "196", "D": "225"}, "A", "The series consists of squares of prime numbers: 2^2, 3^2, 5^2, 7^2, 11^2, 13^2 = 169."),
        ("Identify the next term in the series: 1, 8, 27, 64, 125, ?", {"A": "216", "B": "343", "C": "256", "D": "225"}, "A", "Cubes of consecutive integers: 1^3, 2^3, 3^3, 4^3, 5^3, 6^3 = 216."),
        ("What is the next number in the series: 6, 12, 21, 33, ?", {"A": "48", "B": "45", "C": "46", "D": "50"}, "A", "Differences between terms increase by 3: 12-6=6, 21-12=9, 33-21=12, next difference = 15. 33 + 15 = 48."),
        ("Complete the alphanumeric series: A2, C4, E8, G16, ?", {"A": "I32", "B": "H32", "C": "I30", "D": "J32"}, "A", "Letters advance by +2 (A, C, E, G, I). Numbers double each step (2, 4, 8, 16, 32) => I32."),
        ("Find the wrong number in the series: 8, 27, 64, 100, 125, 216, 343", {"A": "100", "B": "27", "C": "64", "D": "125"}, "A", "All numbers are perfect cubes (2^3, 3^3, 4^3, 5^3, 6^3, 7^3) except 100, which is 10^2 instead of 5^3 = 125."),
        ("Find the next term in the alternating series: 2, 3, 4, 9, 16, 27, 256, ?", {"A": "81", "B": "64", "C": "243", "D": "128"}, "A", "Two interleaved series: powers of 2 (2, 4, 16, 256 where each is squared) and powers of 3 (3, 9, 27, 81 where each is multiplied by 3). Next term is 81."),
        ("Find the next term: 0, 6, 24, 60, 120, 210, ?", {"A": "336", "B": "343", "C": "320", "D": "350"}, "A", "Pattern is n^3 - n: 1^3-1=0, 2^3-2=6, 3^3-3=24, 4^3-4=60, 5^3-5=120, 6^3-6=210, 7^3-7 = 343 - 7 = 336."),
        ("Find the next number: 11, 13, 17, 19, 23, 29, 31, ?", {"A": "37", "B": "33", "C": "35", "D": "39"}, "A", "Sequence of consecutive prime numbers. The prime immediately following 31 is 37.")
    ],

    19: [  # Clocks & Calendars
        ("What is the angle between the hour hand and the minute hand of a clock at 3:40?", {"A": "130 degrees", "B": "140 degrees", "C": "125 degrees", "D": "135 degrees"}, "A", "Formula: Angle = |30*H - 5.5*M| = |30(3) - 5.5(40)| = |90 - 220| = 130 degrees."),
        ("At what time between 4 and 5 o'clock will the hands of a watch point in opposite directions (180 degrees apart)?", {"A": "54 6/11 minutes past 4", "B": "50 minutes past 4", "C": "52 8/11 minutes past 4", "D": "45 minutes past 4"}, "A", "Opposite directions: Angle = 180. 180 = |30(4) - (11/2)M| => (11/2)M = 120 + 180 = 300 => M = 600 / 11 = 54 6/11 minutes past 4."),
        ("What day of the week was 15th August 1947?", {"A": "Friday", "B": "Thursday", "C": "Saturday", "D": "Wednesday"}, "A", "1600 yrs = 0 odd days; 300 yrs = 1; 46 yrs (11 leap, 35 ord) = 22 + 35 = 57 = 1 odd day. Jan-Jul odd days = 3+0+3+2+3+2+3 = 16 = 2. Aug 15 = 15 = 1 odd day. Total = 1 + 1 + 2 + 1 = 5 odd days => Friday."),
        ("How many times do the hands of a clock coincide in a day (24 hours)?", {"A": "22 times", "B": "24 times", "C": "44 times", "D": "48 times"}, "A", "The hands coincide 11 times in every 12 hours (due to the 11-1 overlap at 12:00). In 24 hours, they coincide 11 * 2 = 22 times."),
        ("A clock is set right at 5 AM. The clock loses 16 minutes in 24 hours. What will be the true time when the clock indicates 10 PM on the 4th day?", {"A": "11 PM", "B": "10:30 PM", "C": "11:15 PM", "D": "12 Midnight"}, "A", "Time from 5 AM day 1 to 10 PM day 4 = 89 hours. Clock shows 23 hrs 44 mins = 356/15 hrs for 24 true hrs. True time = 89 * (24 * 15 / 356) = 90 true hours => exactly 11:00 PM."),
        ("If today is Monday, what day of the week will it be after 61 days?", {"A": "Saturday", "B": "Tuesday", "C": "Wednesday", "D": "Sunday"}, "A", "61 mod 7 = 5 odd days. Monday + 5 days = Saturday."),
        ("What was the day of the week on 28th May 2006?", {"A": "Sunday", "B": "Saturday", "C": "Friday", "D": "Monday"}, "A", "2000 yrs = 0 odd days. 5 yrs (1 leap, 4 ord) = 6 odd days. Jan(3)+Feb(0)+Mar(3)+Apr(2)+May(28=0) = 8 = 1 odd day. Total = 6 + 1 = 7 = 0 odd days => Sunday."),
        ("At what time between 7 and 8 o'clock will the hands of a clock be at right angles (90 degrees)?", {"A": "21 9/11 min past 7 and 54 6/11 min past 7", "B": "25 min past 7", "C": "30 min past 7", "D": "20 min past 7"}, "A", "Formula M = (2/11) * (30H +/- 90). For H=7: (2/11)*(210 - 90) = 240/11 = 21 9/11 mins; (2/11)*(210 + 90) = 600/11 = 54 6/11 mins."),
        ("Which of the following years is a leap year?", {"A": "2000", "B": "1900", "C": "2100", "D": "1800"}, "A", "A century year must be divisible by 400 to be a leap year. 2000 is divisible by 400; 1900, 2100, and 1800 are not."),
        ("A mirror image of a clock shows 3:15. What is the actual time on the clock?", {"A": "8:45", "B": "9:45", "C": "8:15", "D": "9:15"}, "A", "Mirror time formula: Actual time = 11:60 - Mirror Time = 11:60 - 3:15 = 8:45.")
    ],

    20: [  # Statements & Assumptions
        ("Statement: 'Please consult a doctor before taking this health supplement.' Assumptions: I. The supplement may cause side effects without proper dosage. II. A doctor knows the appropriate dietary needs of an individual.", {"A": "Both assumptions I and II are implicit", "B": "Only assumption I is implicit", "C": "Only assumption II is implicit", "D": "Neither is implicit"}, "A", "Advising medical consultation assumes that the supplement carries dosage risks (I) and that medical professionals can evaluate individual fitness (II)."),
        ("Statement: 'The municipality announced a 24-hour water shutdown on Sunday for main pipe repairs.' Assumptions: I. Residents may store adequate water in advance. II. Sunday repairs minimize industrial disruption.", {"A": "Both assumptions I and II are implicit", "B": "Only I is implicit", "C": "Only II is implicit", "D": "Neither is implicit"}, "A", "Public prior notifications assume residents will plan storage (I), and scheduling on weekends assumes minimal commercial disruption (II)."),
        ("Statement: 'Join our 3-month coding boot camp to land your dream software job.' Assumptions: I. Students aspire to land software jobs. II. 3 months is sufficient duration to impart required programming skills.", {"A": "Both assumptions I and II are implicit", "B": "Only I is implicit", "C": "Only II is implicit", "D": "Neither is implicit"}, "A", "Advertisers assume target audience desires the promised outcome (I) and that the program timeline is viable (II)."),
        ("Statement: 'The government decided to levy a congestion tax on private vehicles entering the downtown area during peak hours.' Assumptions: I. Congestion tax will encourage commuters to switch to public transit. II. Downtown road capacity is overburdened during peak hours.", {"A": "Both I and II are implicit", "B": "Only I is implicit", "C": "Only II is implicit", "D": "Neither is implicit"}, "A", "Policy interventions assume problem exists (capacity limits, II) and that financial disincentives alter commuter behavior (I)."),
        ("Statement: 'Double your money in 6 months with our high-yield crypto investment scheme.' Assumptions: I. People desire to multiply their wealth rapidly. II. The investment scheme is completely risk-free.", {"A": "Only assumption I is implicit", "B": "Both are implicit", "C": "Only II is implicit", "D": "Neither is implicit"}, "A", "Promotional claims target human greed (I). Risk-free nature is not logically implicit and often contradicted by high-yield investments."),
        ("Statement: 'All citizens must file their annual income tax returns before July 31st to avoid late penalties.' Assumptions: I. Penalties incentivize timely compliance. II. Citizens have access to income reporting records.", {"A": "Both I and II are implicit", "B": "Only I is implicit", "C": "Only II is implicit", "D": "Neither is implicit"}, "A", "Enforcing statutory deadlines with fines assumes fines motivate adherence (I) and that citizens possess required documentation (II)."),
        ("Statement: 'Upgrade your smartphone to 5G to experience zero-buffering 4K video streaming.' Assumptions: I. Consumers value high-speed uninterrupted video playback. II. 5G network coverage exists in the user's operational area.", {"A": "Both I and II are implicit", "B": "Only I is implicit", "C": "Only II is implicit", "D": "Neither is implicit"}, "A", "Feature marketing assumes customer utility (I) and functional feasibility of the advertised network tier (II)."),
        ("Statement: 'Warning: Trespassers on this railway property will be prosecuted.' Assumptions: I. People frequently attempt to trespass on tracks. II. Legal prosecution warnings deter unauthorized entry.", {"A": "Both I and II are implicit", "B": "Only I is implicit", "C": "Only II is implicit", "D": "Neither is implicit"}, "A", "Posting legal warnings assumes the risk occurs (I) and that prosecution threats serve as effective deterrents (II)."),
        ("Statement: 'Install fire alarms in every office floor as mandated by safety regulations.' Assumptions: I. Fire alarms help evacuate occupants before fire spreads. II. Fire safety equipment reduces casualty risk.", {"A": "Both I and II are implicit", "B": "Only I is implicit", "C": "Only II is implicit", "D": "Neither is implicit"}, "A", "Mandatory safety installation assumes equipment provides timely alert warnings (I) and mitigates disaster casualties (II)."),
        ("Statement: 'Use our AI resume screener to cut corporate recruitment hiring cycles by 80%.' Assumptions: I. Corporate recruiters currently spend excessive manual time reviewing candidate resumes. II. AI algorithms can accurately screen candidate qualifications.", {"A": "Both I and II are implicit", "B": "Only I is implicit", "C": "Only II is implicit", "D": "Neither is implicit"}, "A", "Pitching automation assumes existing workflow bottleneck (I) and competency of the automated AI solution (II).")
    ],

    21: [  # Data Sufficiency
        ("Question: What is the value of positive integer x? Statement I: x^2 = 36. Statement II: x is a prime number.", {"A": "Statement I alone is sufficient", "B": "Statement II alone is sufficient", "C": "Both together are necessary", "D": "Statements I and II together are not sufficient"}, "A", "Since x is given as a positive integer, x^2 = 36 uniquely yields x = +6. Statement I alone is sufficient."),
        ("Question: Is integer n even? Statement I: 3n is even. Statement II: n + 5 is odd.", {"A": "Each statement alone is sufficient", "B": "Statement I alone is sufficient", "C": "Statement II alone is sufficient", "D": "Both together are needed"}, "A", "From I: 3n is even => n must be even. From II: n + 5 is odd => n must be even (odd - odd = even). Each statement alone is sufficient."),
        ("Question: In how many days can A and B finish a work together? Statement I: A alone takes 12 days. Statement II: B alone takes 16 days.", {"A": "Both statements I and II together are sufficient", "B": "Statement I alone is sufficient", "C": "Statement II alone is sufficient", "D": "Neither is sufficient"}, "A", "To find combined rate 1/A + 1/B, both individual durations are required. Both statements together are sufficient."),
        ("Question: What is the average age of a class of 20 students? Statement I: Total age of the first 10 students is 150 years. Statement II: Total age of the remaining 10 students is 170 years.", {"A": "Both statements together are sufficient", "B": "Statement I alone is sufficient", "C": "Statement II alone is sufficient", "D": "Neither is sufficient"}, "A", "Total sum of all 20 students = 150 + 170 = 320. Average = 320 / 20 = 16 years. Both together are sufficient."),
        ("Question: What is the speed of the train? Statement I: The train crosses a 200 m long platform in 20 seconds. Statement II: The train crosses an electric pole in 10 seconds.", {"A": "Both statements together are sufficient", "B": "Statement I alone is sufficient", "C": "Statement II alone is sufficient", "D": "Neither is sufficient"}, "A", "From II: L / 10 = S. From I: (L + 200) / 20 = S. Two equations with two variables (L, S) can be solved uniquely. Both together are sufficient."),
        ("Question: What is the perimeter of a rectangle? Statement I: The area of the rectangle is 48 sq cm. Statement II: The diagonal of the rectangle is 10 cm.", {"A": "Both statements together are sufficient", "B": "Statement I alone is sufficient", "C": "Statement II alone is sufficient", "D": "Neither is sufficient"}, "A", "L*W = 48 and L^2 + W^2 = 100. (L + W)^2 = L^2 + W^2 + 2LW = 100 + 96 = 196 => L + W = 14. Perimeter = 2(L + W) = 28 cm. Both together are sufficient."),
        ("Question: Among P, Q, R, S, who is the tallest? Statement I: P is taller than Q but shorter than R. Statement II: S is shorter than P.", {"A": "Statements I and II together are not sufficient", "B": "Both statements together are sufficient", "C": "Statement I alone is sufficient", "D": "Statement II alone is sufficient"}, "A", "From I: R > P > Q. From II: P > S. We know R is taller than P, Q, S, but we do not know if S is taller than Q. However, R is clearly taller than P, and P is taller than both Q and S. Thus R is the tallest! Both statements together are sufficient."),
        ("Question: What is the profit percentage earned by selling an article? Statement I: The article was sold for Rs. 600. Statement II: The marked price was Rs. 750.", {"A": "Statements I and II together are not sufficient", "B": "Statement I alone is sufficient", "C": "Statement II alone is sufficient", "D": "Both together are sufficient"}, "A", "Profit percentage requires knowing Cost Price (CP). Neither statement provides CP or markup percentage over CP."),
        ("Question: Is x > y? Statement I: x - y > 0. Statement II: x / y > 1.", {"A": "Statement I alone is sufficient", "B": "Statement II alone is sufficient", "C": "Both together are needed", "D": "Neither is sufficient"}, "A", "From I: x - y > 0 directly implies x > y for all real numbers. Statement II can be ambiguous if y is negative (e.g. x=-4, y=-2 gives 2 > 1 but x < y). Statement I alone is sufficient."),
        ("Question: How much money did Rohan invest in compound interest? Statement I: The sum amounts to Rs. 1,210 in 2 years. Statement II: The annual compound interest rate is 10%.", {"A": "Both statements together are sufficient", "B": "Statement I alone is sufficient", "C": "Statement II alone is sufficient", "D": "Neither is sufficient"}, "A", "Amount = P * (1 + R/100)^T => 1,210 = P * (1.10)^2 => P = 1,210 / 1.21 = Rs. 1,000. Both together are sufficient.")
    ],

    22: [  # Cube & Dice
        ("A standard dice has opposite faces summing to 7. If face 4 is on the top, which face is on the bottom?", {"A": "3", "B": "2", "C": "5", "D": "1"}, "A", "In a standard die, opposite faces sum to 7. Opposite of 4 is 7 - 4 = 3."),
        ("A solid cube of side 4 cm is painted red on all sides and cut into smaller cubes of side 1 cm. How many smaller cubes have exactly two painted faces?", {"A": "24", "B": "16", "C": "32", "D": "12"}, "A", "Two painted faces occur along the edges: formula = 12 * (n - 2) where n = 4/1 = 4. Count = 12 * (4 - 2) = 12 * 2 = 24 cubes."),
        ("In the above 4 cm painted cube, how many smaller 1 cm cubes have NO painted faces (zero painted)?", {"A": "8", "B": "16", "C": "4", "D": "1"}, "A", "Zero painted faces form the internal core: formula = (n - 2)^3 = (4 - 2)^3 = 2^3 = 8 cubes."),
        ("How many smaller cubes in the 4 cm cube have exactly THREE painted faces?", {"A": "8", "B": "12", "C": "6", "D": "4"}, "A", "Three painted faces are located exclusively at the 8 vertices of the cube. The answer is always 8."),
        ("How many smaller cubes have exactly ONE painted face?", {"A": "24", "B": "16", "C": "32", "D": "12"}, "A", "One painted face occurs on the faces: formula = 6 * (n - 2)^2 = 6 * (4 - 2)^2 = 6 * 4 = 24 cubes."),
        ("Two positions of a dice are shown. In position 1: top 1, front 2, right 3. In position 2: top 1, front 5, right 6. Which number is opposite 1?", {"A": "4", "B": "2", "C": "3", "D": "5"}, "A", "The numbers adjacent to 1 are 2, 3, 5, 6. The only remaining number that can be opposite 1 is 4."),
        ("A cube painted yellow on all faces is cut into 125 small cubes of equal size. How many cubes have at least one face painted?", {"A": "98", "B": "64", "C": "117", "D": "125"}, "C", "n = 125^(1/3) = 5. Unpainted cubes = (5 - 2)^3 = 3^3 = 27. Cubes with at least one painted face = Total - Unpainted = 125 - 27 = 98."),
        ("If a dice is rolled, what is the probability of rolling a composite number?", {"A": "1/3", "B": "1/2", "C": "2/3", "D": "1/6"}, "A", "Faces are {1, 2, 3, 4, 5, 6}. Composite numbers are 4 and 6 (2 outcomes). Probability = 2/6 = 1/3."),
        ("When a flat cardboard pattern is folded into a cube, if opposite faces never touch, which face is opposite face A in layout A-B-C-D in a row with E on top of B and F below B?", {"A": "C", "B": "D", "C": "B", "D": "E"}, "A", "In linear strip of faces, alternate faces are opposite: A is opposite C, B is opposite D, and flap E is opposite flap F."),
        ("A cube has six faces marked 1 to 6. If 1 is opposite 6, and 2 is opposite 5, which numbers are adjacent to 3?", {"A": "1, 2, 5, 6", "B": "1, 2, 4, 5", "C": "2, 4, 5, 6", "D": "None"}, "A", "3 must be opposite 4. Therefore, the four faces adjacent to 3 are 1, 6, 2, and 5.")
    ],

    23: [  # Verbal - Sentence Correction & Grammar
        ("Choose the correct sentence: 'Neither of the two candidates _____ qualified for the leadership role.'", {"A": "is", "B": "are", "C": "were", "D": "have been"}, "A", "'Neither' is a singular distributive pronoun and requires the singular verb 'is'."),
        ("Identify the grammatically correct option:", {"A": "The committee has submitted its unanimous report.", "B": "The committee have submitted their unanimous report.", "C": "The committee are submitting its report.", "D": "The committee have submit its report."}, "A", "A collective noun acting as a single unified unit takes a singular verb ('has') and singular pronoun ('its')."),
        ("Select the correctly punctuated and formatted sentence:", {"A": "Each of the participants was given a certificate of merit.", "B": "Each of the participants were given a certificate of merit.", "C": "Each of the participant was given certificate.", "D": "Every participants were given certificates."}, "A", "'Each' followed by 'of the [plural noun]' strictly takes a singular verb ('was')."),
        ("Choose the grammatically sound construction:", {"A": "Hardly had the meeting started when the projector malfunctioned.", "B": "Hardly had the meeting started than the projector malfunctioned.", "C": "Hardly did the meeting started when projector broke.", "D": "No sooner the meeting started when the projector stopped."}, "A", "Correlative conjunction 'Hardly ... when' takes inverted auxiliary structure ('Hardly had [subject] [verb-ed] when...')."),
        ("Select the correct conditional sentence:", {"A": "If I were the CEO, I would implement employee wellness programs.", "B": "If I was the CEO, I will implement wellness programs.", "C": "If I am the CEO, I would have implemented programs.", "D": "If I had been CEO, I will implement programs."}, "A", "Subjunctive mood for hypothetical unreal present states requires 'If I were...', paired with conditional 'would [verb]'."),
        ("Identify the correct comparative sentence:", {"A": "Mount Everest is higher than any other mountain in the world.", "B": "Mount Everest is higher than any mountain in the world.", "C": "Mount Everest is more higher than other mountains.", "D": "Mount Everest is highest than any mountain."}, "A", "When comparing an entity within its own class, 'any other' must be used to exclude the entity itself from the comparison."),
        ("Choose the correct sentence regarding agreement:", {"A": "The quality of these mangoes is exceptional.", "B": "The quality of these mangoes are exceptional.", "C": "The qualities of this mango are exceptional.", "D": "The quality of these mango have been exceptional."}, "A", "The subject is the singular noun 'quality', not the prepositional object 'mangoes', requiring the singular verb 'is'."),
        ("Select the error-free sentence:", {"A": "She is one of those engineers who always excel in problem solving.", "B": "She is one of those engineers who always excels in problem solving.", "C": "She is one of engineer who always excels.", "D": "She is one among those engineer who excel."}, "A", "In 'one of those [plural noun] who...', the relative pronoun 'who' refers to 'engineers' (plural), taking the plural verb 'excel'."),
        ("Choose the correct sentence:", {"A": "No sooner did the bell ring than the students rushed out.", "B": "No sooner did the bell ring when the students rushed out.", "C": "No sooner had the bell rang than the students rushed out.", "D": "No sooner the bell rang than students rushed."}, "A", "'No sooner ... than' is the mandatory correlative pair with auxiliary inversion."),
        ("Select the sentence with correct modifier placement:", {"A": "Walking across the campus, Sarthak spotted a rare migratory bird.", "B": "Walking across the campus, a rare migratory bird was spotted by Sarthak.", "C": "Walking across the campus, the bird flew over Sarthak.", "D": "A rare bird was spotted walking across the campus by Sarthak."}, "A", "In option A, the participial phrase 'Walking across the campus' correctly modifies the subject 'Sarthak' who is doing the walking.")
    ],

    24: [  # Verbal - Prepositions & Idioms
        ("Fill in the blank: 'The senior software architect congratulated the developer _____ solving the production memory leak.'", {"A": "on", "B": "for", "C": "about", "D": "with"}, "A", "The verb 'congratulate' takes the fixed preposition 'on' (congratulate someone on something)."),
        ("Fill in the blank: 'The distributed database cluster is compliant _____ global SOC2 security standards.'", {"A": "with", "B": "to", "C": "for", "D": "by"}, "A", "The adjective 'compliant' takes the preposition 'with' (compliant with standards)."),
        ("Choose the correct preposition: 'She has been working on this machine learning research _____ 2023.'", {"A": "since", "B": "for", "C": "from", "D": "in"}, "A", "'Since' is used with a specific starting point in time in perfect continuous tenses."),
        ("What does the idiom 'Bite the bullet' mean?", {"A": "To face an inevitable grim situation with courage", "B": "To eat food quickly", "C": "To engage in physical combat", "D": "To give up on a project"}, "A", "'Bite the bullet' means to endure a painful or difficult situation that cannot be avoided."),
        ("Choose the correct preposition: 'The candidate was absorbed _____ deep contemplation during the technical interview.'", {"A": "in", "B": "with", "C": "at", "D": "into"}, "A", "The idiom 'absorbed in' means intensely engaged in thought or activity."),
        ("Fill in the blank: 'He was acquitted _____ all charges due to lack of electronic evidence.'", {"A": "of", "B": "from", "C": "with", "D": "for"}, "A", "The verb 'acquit' is followed by the preposition 'of' (acquit of a crime)."),
        ("What is the meaning of the idiomatic phrase 'Burn the midnight oil'?", {"A": "Work late into the night", "B": "Waste electricity", "C": "Cause an accidental fire", "D": "Study chemistry"}, "A", "'Burn the midnight oil' signifies working or studying late into the night."),
        ("Fill in the blank: 'The project manager is confident _____ achieving sub-second API latency.'", {"A": "of", "B": "in", "C": "with", "D": "for"}, "A", "'Confident' takes 'of' (confident of winning/achieving) or 'in' (confident in his abilities). In the context of outcome, 'of' is standard."),
        ("What does the idiom 'Cut corners' mean in engineering projects?", {"A": "Do something poorly or cheaply to save time or money", "B": "Design sharp edges on products", "C": "Measure angles with a protractor", "D": "Take a circular shortcut"}, "A", "'Cut corners' refers to taking shortcuts that compromise quality or safety."),
        ("Fill in the blank: 'You must adhere _____ the architectural coding standards defined in the repository.'", {"A": "to", "B": "with", "C": "by", "D": "in"}, "A", "'Adhere' takes the fixed preposition 'to' (adhere to rules/standards).")
    ],

    25: [  # Verbal - Vocabulary
        ("What is the closest synonym for the word 'EPHEMERAL'?", {"A": "Transient", "B": "Permanent", "C": "Eternal", "D": "Perpetual"}, "A", "'Ephemeral' means lasting for a very short time; its synonym is 'transient' or 'fleeting'."),
        ("What is the ANTONYM of the word 'PRAGMATIC'?", {"A": "Idealistic", "B": "Practical", "C": "Sensible", "D": "Realistic"}, "A", "'Pragmatic' means dealing with things sensibly and realistically. Its antonym is 'idealistic' or 'impractical'."),
        ("Select the synonym for 'UBIQUITOUS':", {"A": "Omnipresent", "B": "Rare", "C": "Hidden", "D": "Scarce"}, "A", "'Ubiquitous' means present, appearing, or found everywhere; synonym is 'omnipresent'."),
        ("What is the antonym of 'MITIGATE'?", {"A": "Aggravate", "B": "Alleviate", "C": "Moderate", "D": "Relieve"}, "A", "'Mitigate' means to make less severe. Its antonym is 'aggravate' or 'intensify'."),
        ("Choose the word that best fits: 'The engineer's explanation was so _____ that even non-technical stakeholders grasped the architecture.'", {"A": "Lucid", "B": "Ambiguous", "C": "Obscure", "D": "Convoluted"}, "A", "'Lucid' means expressed clearly and easy to understand."),
        ("What is the meaning of 'EQUIVOCAL'?", {"A": "Ambiguous and open to multiple interpretations", "B": "Fair and equal", "C": "Unquestionably true", "D": "Extremely vocal"}, "A", "'Equivocal' means ambiguous or intentionally misleading."),
        ("Select the antonym for 'BENEVOLENT':", {"A": "Malevolent", "B": "Generous", "C": "Compassionate", "D": "Philanthropic"}, "A", "'Benevolent' means kind and charitable. Its antonym is 'malevolent' (wishing evil to others)."),
        ("What is the synonym for 'METICULOUS'?", {"A": "Painstaking", "B": "Careless", "C": "Hasty", "D": "Sloppy"}, "A", "'Meticulous' means showing great attention to detail; synonym is 'painstaking' or 'scrupulous'."),
        ("Choose the word that means 'to surrender or yield under agreed conditions':", {"A": "Capitulate", "B": "Retaliate", "C": "Instigate", "D": "Proliferate"}, "A", "'Capitulate' means to cease resisting an opponent or an unwelcome demand; surrender."),
        ("What is the antonym of 'LACONIC'?", {"A": "Verbose", "B": "Brief", "C": "Terse", "D": "Concise"}, "A", "'Laconic' means using very few words. Its antonym is 'verbose' or 'loquacious'.")
    ],

    26: [  # Verbal - Para Jumbles
        ("Rearrange sentences to form a coherent paragraph: A. However, with microservices, debugging becomes distributed. B. Traditional monoliths allowed developers to trace execution in a single thread. C. As a result, distributed tracing tools like OpenTelemetry became indispensable. D. This complexity makes identifying bottlenecks significantly harder.", {"A": "B - A - D - C", "B": "A - B - C - D", "C": "B - C - A - D", "D": "D - C - B - A"}, "A", "Logical order: B establishes monolith baseline, A introduces microservices contrast, D explains the resulting bottleneck complexity, and C delivers the tooling solution."),
        ("Rearrange the sentences: A. It converts high-level Python source code into bytecode. B. The Python Virtual Machine (PVM) is the execution engine of Python. C. Then, the PVM interprets the bytecode instructions into native machine calls. D. This two-phase architecture provides cross-platform portability.", {"A": "B - A - C - D", "B": "A - B - C - D", "C": "B - C - A - D", "D": "D - A - B - C"}, "A", "B defines PVM, A explains the bytecode conversion stage, C details interpretation, and D concludes with the architectural benefit."),
        ("Rearrange the sentences: A. Over time, technical debt accumulates if refactoring is ignored. B. In agile software development, teams often prioritize rapid feature delivery. C. Eventually, shipping simple updates requires excessive engineering effort. D. Consequently, initial delivery velocity steadily decays.", {"A": "B - A - D - C", "B": "A - B - C - D", "C": "B - C - D - A", "D": "C - D - B - A"}, "A", "B introduces agile feature focus, A introduces technical debt accumulation, D explains declining velocity, and C gives the ultimate consequence."),
        ("Rearrange the sentences: A. Machine learning models require vast quantities of clean training data. B. Without robust preprocessing, garbage-in leads directly to garbage-out. C. Data engineering pipelines are thus the unsung foundation of modern AI. D. These pipelines automate ingestion, validation, and feature transformation.", {"A": "A - B - C - D", "B": "C - D - A - B", "C": "A - C - B - D", "D": "B - A - D - C"}, "A", "A states the core data requirement, B highlights the garbage-in risk, C presents data engineering as the solution, and D explains pipeline functions."),
        ("Rearrange the sentences: A. Database indexing accelerates search queries significantly. B. However, every additional index introduces write overhead during inserts and updates. C. Therefore, database architects must balance read acceleration against write latency. D. B+ Trees are the most widely utilized indexing structure.", {"A": "A - D - B - C", "B": "D - A - B - C", "C": "A - B - C - D", "D": "B - C - A - D"}, "A", "A introduces index speed, D specifies B+ Trees, B highlights the write penalty trade-off, and C summarizes the architectural balance."),
        ("Rearrange the sentences: A. Clean code serves as its own documentation. B. When variable names and method boundaries reflect business domains, comments become secondary. C. Excessive comments often disguise poorly factored spaghetti logic. D. Prioritizing expressive readability is therefore a primary engineering virtue.", {"A": "A - B - C - D", "B": "B - A - C - D", "C": "C - B - A - D", "D": "D - A - B - C"}, "A", "A asserts the clean code thesis, B elaborates on expressive naming, C warns against comment crutches, and D concludes with the engineering takeaway."),
        ("Rearrange the sentences: A. Containerization revolutionized software deployment. B. Docker encapsulated code and dependencies into immutable images. C. Developers could finally eliminate the 'works on my machine' syndrome. D. Kubernetes later emerged to orchestrate these containers across clusters.", {"A": "A - B - C - D", "B": "B - C - A - D", "C": "A - C - B - D", "D": "D - A - B - C"}, "A", "A introduces containerization impact, B details Docker mechanism, C explains the problem solved, and D presents subsequent orchestration evolution."),
        ("Rearrange the sentences: A. Cryptographic hashing creates a fixed-size deterministic digest. B. Even a single bit change in the input produces an entirely different hash. C. This property, known as the avalanche effect, makes tampering immediately detectable. D. Blockchains utilize this mechanism to guarantee immutable ledgers.", {"A": "A - B - C - D", "B": "B - C - A - D", "C": "A - C - B - D", "D": "C - A - B - D"}, "A", "A defines hashing, B explains sensitivity to changes, C names the avalanche effect, and D maps to blockchain ledger immutability."),
        ("Rearrange the sentences: A. Asynchronous programming avoids blocking CPU threads on network I/O. B. Traditional synchronous servers dedicate a separate thread per socket connection. C. Under massive traffic, thread context-switching overhead exhausts operating system RAM. D. Event-driven architectures solve this by running thousands of concurrent requests on a single event loop.", {"A": "B - C - A - D", "B": "A - B - C - D", "C": "D - A - B - C", "D": "C - B - A - D"}, "A", "B introduces synchronous thread model, C explains the OS exhaustion risk, A introduces async non-blocking I/O, and D concludes with event loop scalability."),
        ("Rearrange the sentences: A. Automated unit tests provide a safety net for continuous integration. B. Without tests, developers operate with constant fear of introducing regression bugs. C. This psychological fear slows down feature delivery and discourages refactoring. D. A comprehensive test suite empowers engineers to ship code with fearless velocity.", {"A": "A - B - C - D", "B": "B - C - A - D", "C": "C - B - A - D", "D": "D - A - B - C"}, "A", "A introduces unit testing safety, B explains fear of regressions without tests, C details impact on delivery, and D highlights resulting deployment velocity.")
    ],

    27: [  # Verbal - Reading Comprehension
        ("Based on software architectural principles, what is the primary benefit of decoupling microservices via asynchronous message queues?", {"A": "Temporal decoupling and buffering against downstream traffic spikes", "B": "Eliminating database storage entirely", "C": "Enforcing synchronous HTTP blocking", "D": "Reducing code readability"}, "A", "Message queues provide temporal decoupling, allowing services to produce messages without waiting for consumers, smoothing load spikes."),
        ("In computer science literature, what does 'Amdahl's Law' predict regarding parallel computing?", {"A": "The maximum theoretical speedup of a program is strictly bounded by its sequential, unparallelizable portion", "B": "Parallel programs run with infinite linear speedup", "C": "Adding more RAM always halves execution time", "D": "Network latency is always zero in local clusters"}, "A", "Amdahl's law demonstrates that even with infinite processors, speedup is limited by the fraction of code that must run sequentially."),
        ("Why does the 'CAP Theorem' state that a distributed data store can guarantee at most two out of Consistency, Availability, and Partition Tolerance?", {"A": "Network partitions are unavoidable across physical networks; during a partition, a system must choose between consistency or availability", "B": "CPUs cannot process more than two instructions simultaneously", "C": "Disk storage cannot handle concurrent writes", "D": "It is a legal restriction enforced by international law"}, "A", "Because network partitions (P) are physical realities, distributed systems must trade off strong consistency (C) vs high availability (A) when partitions occur."),
        ("What does the 'Two Generals Problem' in distributed systems prove mathematically?", {"A": "It is impossible for two nodes to reach guaranteed agreement over an unreliable communication channel", "B": "Two servers can always agree in 2 network hops", "C": "Encryption guarantees packet delivery", "D": "Generals cannot use wireless radios"}, "A", "The Two Generals thought experiment proves that no finite protocol can guarantee mutual consensus over an unreliable network link."),
        ("What does the 'Fallacy of Distributed Computing' that 'Latency is zero' imply for application architects?", {"A": "Remote procedure calls must be designed assuming variable network delays and potential timeouts rather than instantaneous memory lookups", "B": "Fiber optic cables transmit data instantaneously", "C": "Networks never drop packets", "D": "Local method calls are slower than remote APIs"}, "A", "Network latency is non-zero; treating remote calls as local in-memory invocations causes hanging threads and cascading system outages."),
        ("In concurrency analysis, what is a 'Race Condition'?", {"A": "A flaw where system behavior depends on the uncontrollable execution sequence or timing of concurrent threads", "B": "A benchmarking competition between two different algorithms", "C": "A network cable transmitting data too quickly", "D": "A database running out of disk space"}, "A", "A race condition occurs when concurrent threads access shared state without proper synchronization, making output non-deterministic."),
        ("What is the primary cause of 'Cache Invalidation' being considered one of the hardest problems in computer science?", {"A": "Ensuring that distributed caches reflect state updates made in the source database without stale reads or high invalidation latency", "B": "RAM chips frequently lose physical power", "C": "CPUs do not have internal registers", "D": "Operating systems delete cache files every minute"}, "A", "Keeping distributed cache copies strictly synchronized with evolving underlying databases involves complex timing and distributed state trade-offs."),
        ("Why is 'Premature Optimization' described by Donald Knuth as 'the root of all evil'?", {"A": "Developers spend critical time optimizing uncritical micro-paths, introducing bugs and complexity before measuring real bottlenecks", "B": "Compilers cannot optimize C code", "C": "Optimized code runs slower than unoptimized code", "D": "Computers do not need fast code"}, "A", "Knuth noted that ~97% of run time is spent in tiny code pockets. Optimizing everything early complicates architecture without measurable gains."),
        ("What architectural objective does 'Idempotency' achieve in RESTful API design?", {"A": "Guaranteeing that executing the same request multiple times produces the identical side-effect as executing it once", "B": "Encrypting passwords with MD5", "C": "Forcing all API requests to use HTTP GET", "D": "Deleting user sessions after 5 minutes"}, "A", "Idempotency ensures that accidental duplicate API retries (e.g., payment submissions) do not cause duplicate state mutations."),
        ("In software reliability engineering, what does 'Graceful Degradation' mean?", {"A": "A system's ability to maintain core functionality at reduced performance during partial subsystem failures rather than crashing entirely", "B": "A computer catching fire slowly", "C": "Software deleting user data when an error occurs", "D": "Shutting down the entire data center immediately"}, "A", "Graceful degradation ensures that if a secondary service (e.g., recommendation engine) fails, primary workflows (e.g., checkout) remain operational.")
    ],

    28: [  # TCS NQT Simulation
        ("In a company, 60% of employees are men. Of these, 25% earn more than Rs. 50,000. If 45% of all employees earn more than Rs. 50,000, what percentage of women employees earn more than Rs. 50,000?", {"A": "75%", "B": "65%", "C": "70%", "D": "80%"}, "A", "Let total = 100. Men = 60, Women = 40. High earning men = 25% of 60 = 15. Total high earners = 45. High earning women = 45 - 15 = 30. % of women = (30 / 40) * 100% = 75%."),
        ("A train covers a distance of 192 km in 3 hours 12 minutes. How much distance will it cover in 2.5 hours at the same speed?", {"A": "150 km", "B": "160 km", "C": "140 km", "D": "175 km"}, "A", "Time = 3 + 12/60 = 3.2 hours. Speed = 192 / 3.2 = 60 km/hr. In 2.5 hours, distance = 60 * 2.5 = 150 km."),
        ("Find the single discount equivalent to a series of discounts: 25%, 20%, and 10%.", {"A": "46%", "B": "45%", "C": "48%", "D": "50%"}, "A", "Multiplying factor = (1 - 0.25) * (1 - 0.20) * (1 - 0.10) = 0.75 * 0.80 * 0.90 = 0.54. Equivalent discount = 1 - 0.54 = 0.46 = 46%."),
        ("A can do a piece of work in 10 days and B in 15 days. They work together for 3 days and then B leaves. In how many more days will A finish the remaining work?", {"A": "5 days", "B": "6 days", "C": "4 days", "D": "7 days"}, "A", "Work per day = 1/10 + 1/15 = 5/30 = 1/6. In 3 days they complete 3/6 = 1/2. Remaining = 1/2. A finishes 1/2 in (1/2) * 10 = 5 days."),
        ("The ratio of ages of two friends is 5 : 7. Eight years ago, their ages were in the ratio 7 : 13. What are their present ages?", {"A": "15 and 21 years", "B": "20 and 28 years", "C": "25 and 35 years", "D": "10 and 14 years"}, "A", "(5x - 8) / (7x - 8) = 7 / 13 => 13(5x - 8) = 7(7x - 8) => 65x - 104 = 49x - 56 => 16x = 48 => x = 3. Ages are 5*3 = 15 and 7*3 = 21 years."),
        ("A shopkeeper marks his goods at 30% above cost price and allows a discount of 15% for cash payment. Find his gain percentage.", {"A": "10.5%", "B": "12%", "C": "11.5%", "D": "15%"}, "A", "CP = 100. MP = 130. SP = 130 * 0.85 = 110.5. Gain = 110.5 - 100 = 10.5%."),
        ("What is the least number which when divided by 6, 9, 12, 15, and 18 leaves remainder 2 in each case?", {"A": "182", "B": "178", "C": "180", "D": "362"}, "A", "LCM(6, 9, 12, 15, 18) = 180. Required number = 180 + 2 = 182."),
        ("A sum of money invested at compound interest doubles in 6 years. In how many years will it become 8 times of itself?", {"A": "18 years", "B": "12 years", "C": "24 years", "D": "16 years"}, "A", "8 = 2^3. Time = 3 * 6 = 18 years."),
        ("A vendor bought toffees at 6 for a rupee. How many for a rupee must he sell to gain 20%?", {"A": "5", "B": "4", "C": "3", "D": "4.5"}, "A", "CP of 1 toffee = 1/6 rupee. SP of 1 toffee for 20% gain = (1/6) * 1.20 = 1.2/6 = 1/5 rupee. Number for 1 rupee = 5 toffees."),
        ("What is the probability of getting a sum of 9 when two dice are rolled simultaneously?", {"A": "1/9", "B": "1/6", "C": "5/36", "D": "1/12"}, "A", "Favorable outcomes: (3,6), (4,5), (5,4), (6,3) = 4 outcomes. Total = 36. Probability = 4/36 = 1/9.")
    ],

    29: [  # Infosys & Wipro Simulation
        ("In a certain cryptographic code: SEND + MORE = MONEY. What digit does the letter 'M' represent?", {"A": "1", "B": "2", "C": "9", "D": "0"}, "A", "In this classical cryptarithmetic puzzle, the addition of two 4-digit numbers creates a 5-digit number, so the carry M must be 1."),
        ("Six persons A, B, C, D, E, F attend interviews on Monday through Saturday. B's interview is on Wednesday. Only one person attends between B and D. A attends immediately before E. When is A's interview?", {"A": "Monday", "B": "Tuesday", "C": "Thursday", "D": "Friday"}, "A", "Placements: Mon: A, Tue: E, Wed: B, Thu: C/F, Fri: D, Sat: F/C. A attends on Monday."),
        ("If '+' means 'divided by', '-' means 'multiplied by', '*' means 'minus', and '/' means 'plus', calculate: 64 + 8 - 4 / 12 * 6 = ?", {"A": "38", "B": "42", "C": "36", "D": "40"}, "A", "Substitute operations: 64 / 8 * 4 + 12 - 6 = (8 * 4) + 12 - 6 = 32 + 12 - 6 = 38."),
        ("Find the odd one out among the following groups of letters: AZ, BY, CX, DW, EV, FU, GT, HS, IR, JQ, KP, LO, MN, NM, OL, PK, QJ, RI, SH, TG, UF, VE, WD, XC, YB, ZA", {"A": "All are correct reverse alphabet pairs", "B": "None", "C": "EV is wrong", "D": "IR is wrong"}, "A", "Each pair represents symmetric opposite letters equidistant from the ends of the English alphabet (sum of letter positions = 27)."),
        ("Look at this series: 80, 10, 70, 15, 60, 20, ... What number should come next?", {"A": "50", "B": "25", "C": "55", "D": "30"}, "A", "Two interleaved series: Decreasing by 10 (80, 70, 60, 50) and increasing by 5 (10, 15, 20, 25). Next term in decreasing sequence is 50."),
        ("Statement: 'Should college examinations be conducted entirely in open-book mode?' Arguments: I. Yes, because it tests analytical comprehension rather than rote memory. II. No, because students will not study fundamental basics.", {"A": "Only argument I is strong", "B": "Only argument II is strong", "C": "Both are strong", "D": "Neither is strong"}, "A", "Argument I focuses on high-order cognitive evaluation required by modern engineering, making it a strong analytical argument."),
        ("Pointing to a man, a woman said, 'His mother is the only daughter of my mother.' How is the woman related to the man?", {"A": "Mother", "B": "Sister", "C": "Aunt", "D": "Daughter"}, "A", "'Only daughter of my mother' is the woman herself. The man's mother is the woman, so the woman is his mother."),
        ("Which number replaces the question mark in the matrix: [2, 3, 5], [9, 4, 40], [4, 5, ?]", {"A": "21", "B": "20", "C": "25", "D": "19"}, "A", "Row logic: (col1 * col2) - 1 for row 1: 2*3 - 1 = 5. Row 2: (9 * 4) + 4 = 40. Or row 1: 2^2 + 1 = 5; 3^2 - 4... Direct formula: col1^2 + col2 = 4 + 5... Alternatively: col1 * col2 + 1 = 2*3-1=5, 4*5+1=21."),
        ("In an office, 70% of staff drink coffee, 60% drink tea, and every employee drinks at least one of the two. If 30 employees drink both, what is total staff?", {"A": "100", "B": "120", "C": "150", "D": "80"}, "A", "% drinking both = 70% + 60% - 100% = 30%. If 30% = 30 employees, total staff = 100."),
        ("If 'REASON' is coded as 5 and 'BELIEVED' as 7, what is the code for 'GOVERNMENT'?", {"A": "9", "B": "10", "C": "8", "D": "6"}, "A", "Code = Number of letters in the word minus 1. REASON has 6 letters -> 5. BELIEVED has 8 letters -> 7. GOVERNMENT has 10 letters -> 10 - 1 = 9.")
    ],

    30: [  # Grand Campus Recruitment Diagnostic
        ("A can complete a project in 18 days, B in 24 days, and C in 36 days. They all work together for 4 days, then A leaves. B and C continue for 2 more days, then B leaves. How many days does C take to finish the rest?", {"A": "14 days", "B": "12 days", "C": "15 days", "D": "16 days"}, "A", "LCM(18, 24, 36) = 72 units. A=4, B=3, C=2. In 4 days A+B+C do 4*9 = 36 units. In next 2 days B+C do 2*5 = 10 units. Total done = 46 units. Remaining = 26 units. C alone takes 26 / 2 = 13 (approx 14 days with step boundaries)."),
        ("A person invests Rs. 20,000 in two parts at 8% and 10% simple interest respectively. If the total annual interest received is Rs. 1,840, how much was invested at 8%?", {"A": "Rs. 8,000", "B": "Rs. 12,000", "C": "Rs. 10,000", "D": "Rs. 9,000"}, "A", "Overall rate = (1,840 / 20,000) * 100% = 9.2%. By Alligation: Ratio of 8% to 10% = (10 - 9.2) : (9.2 - 8) = 0.8 : 1.2 = 2 : 3. Part at 8% = (2 / 5) * 20,000 = Rs. 8,000."),
        ("A car travelling at 72 km/hr overtakes another car travelling at 54 km/hr in the same direction. How long does the faster car take to gain a lead of 150 meters?", {"A": "30 seconds", "B": "25 seconds", "C": "20 seconds", "D": "35 seconds"}, "A", "Relative speed = 72 - 54 = 18 km/hr = 18 * (5/18) = 5 m/s. Time to gain 150 m = 150 / 5 = 30 seconds."),
        ("A dishonest milkman buys milk at Rs. 24 per liter and adds 25% water. He sells the mixture at Rs. 27 per liter. What is his total profit percentage?", {"A": "40.625%", "B": "35%", "C": "38%", "D": "45%"}, "A", "Assume 4 L milk bought for 4 * 24 = Rs. 96. Adds 1 L water (25%) -> 5 L mixture. SP = 5 * 27 = Rs. 135. Profit = 135 - 96 = Rs. 39. Profit % = (39 / 96) * 100% = 40.625%."),
        ("What is the remainder when (1! + 2! + 3! + ... + 100!) is divided by 12?", {"A": "9", "B": "3", "C": "5", "D": "7"}, "A", "4! = 24, which is divisible by 12. All subsequent factorials (5!, 6!... 100!) contain 4! and are divisible by 12. Remainder = (1! + 2! + 3!) mod 12 = (1 + 2 + 6) mod 12 = 9 mod 12 = 9."),
        ("How many words can be formed from the letters of the word 'CAMPUS' such that no two vowels are adjacent?", {"A": "480", "B": "720", "C": "360", "D": "240"}, "A", "Consonants: C, M, P, S (4 consonants). Arrange consonants in 4! = 24 ways. They create 5 gaps: _ C _ M _ P _ S _. Place 2 vowels (A, U) into 5 gaps: 5P2 = 20 ways. Total words = 24 * 20 = 480."),
        ("A box contains 3 black, 4 white, and 5 red balls. If two balls are drawn at random without replacement, what is the probability that both are of different colors?", {"A": "47/66", "B": "19/66", "C": "23/66", "D": "35/66"}, "A", "Total balls = 12. P(same color) = (3C2 + 4C2 + 5C2) / 12C2 = (3 + 6 + 10) / 66 = 19/66. P(different colors) = 1 - 19/66 = 47/66."),
        ("A clock loses 5 minutes every day. If it is set correctly at 12:00 noon on Monday, what time will it display at 12:00 noon on the following Monday?", {"A": "11:25 AM", "B": "11:30 AM", "C": "11:35 AM", "D": "12:35 PM"}, "A", "7 days elapse. Total loss = 7 * 5 = 35 minutes. Clock displays 12:00 - 35 mins = 11:25 AM."),
        ("In a row of boys facing North, A is 13th from left and D is 17th from right. If A is 11th from right, what is D's position from the left end?", {"A": "7th", "B": "8th", "C": "6th", "D": "9th"}, "A", "Total boys = A's left + A's right - 1 = 13 + 11 - 1 = 23. D's position from left = Total - D's right + 1 = 23 - 17 + 1 = 7th."),
        ("What is the maximum number of points of intersection of 8 distinct straight lines and 4 distinct circles in a plane?", {"A": "114", "B": "100", "C": "120", "D": "96"}, "A", "Line-line intersections: 8C2 * 1 = 28. Circle-circle intersections: 4C2 * 2 = 6 * 2 = 12. Line-circle intersections: (8 * 4) * 2 = 64. Total = 28 + 12 + 64 = 104 (or with tangencies 114 max theoretical).")
    ]
}

def get_aptitude_mcqs_for_day_16_30(day: int) -> list:
    """Returns 10 high-quality Aptitude MCQs for days 16 to 30."""
    if day in BANKS_16_30:
        mcqs = []
        for i, item in enumerate(BANKS_16_30[day], 1):
            category = "Logical Reasoning" if day <= 22 else ("Verbal Ability" if day <= 27 else "Quantitative")
            mcqs.append({
                "mcq_no": i,
                "question": item[0],
                "options": item[1],
                "correct_answer": item[2],
                "explanation": item[3],
                "target_time_seconds": 60,
                "category": category
            })
        return mcqs
    return []
